server:
  port: 8040
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jfteam/spring-cloud-microservice-study/     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 244160190@163.com                           # git仓库的账号
          password: xxxxxxxx                                    # git仓库的密码