server:
  port: 8050
spring:
  application:
    name: microservice-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jfteam/spring-cloud-microservice-study/
          search-paths: config-repo
          username: 244160190@163.com
          password: xxxxxxxx
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery1.jfteam.org:8761/eureka/